const Task = require("../models/Task");
const Reminder = require("../models/Reminder");
const Note = require("../models/Note");
const {
  formatISTDate,
  getISTDateParts,
  istToUTC,
} = require("../utils/dateFormatter");

/**
 * Auto-create reminder and note for a task
 * @param {Object} task - The created task object
 * @returns {Promise<Object>} - Returns the task with reminderId and noteId
 */
async function autoCreateDependencies(task, hasExplicitTime = false) {
  try {
    console.log(`🔄 Auto-creating dependencies for task: "${task.title}"`);

    let reminderId = null;
    let noteId = null;
    let savedReminder = null;
    let savedNote = null;

    // 1. Auto-create reminder (if task has due date)
    if (task.dueDate) {
      const reminderDate = new Date(task.dueDate);

      if (hasExplicitTime) {
        console.log(`  ⏰ Using user-specified time: ${reminderDate}`);
      } else {
        const utcDate = new Date(task.dueDate);

        // Convert UTC to IST by adding 5:30 to get the correct date
        const istDate = new Date(utcDate.getTime() + 5.5 * 60 * 60 * 1000);

        // Set to 9 AM IST
        istDate.setHours(9, 0, 0, 0);

        // Convert back to UTC for storage
        reminderDate.setTime(istDate.getTime() - 5.5 * 60 * 60 * 1000);

        console.log(
          `  ⏰ Default time (9 AM IST) set to UTC: ${reminderDate.toISOString()}`,
        );
      }
      console.log(`  ⏰ Reminder will be set for: ${reminderDate}`);
      const reminderTitle = `${task.title}`;
      const reminder = new Reminder({
        title: reminderTitle,
        remindAt: reminderDate,
        taskId: task._id,
        isAutoGenerated: true,
      });

      savedReminder = await reminder.save();
      reminderId = savedReminder._id;
      console.log(
        `  ✅ Reminder created: "${reminderTitle}" with ID: ${reminderId}`,
      );
    } else {
      console.log(`  ⚠️ No due date, skipping reminder creation`);
    }

    // 2. Auto-create note
    const noteTitle = `${task.title}`;
    const noteContent = `Task: ${task.title}\nPriority: ${task.priority}\nCreated: ${formatISTDate(new Date())}\n\n---\nAdd your notes here...`;
    const note = new Note({
      title: noteTitle,
      content: noteContent,
      taskId: task._id,
      isAutoGenerated: true,
    });

    savedNote = await note.save();
    noteId = savedNote._id;
    console.log(`  ✅ Note created: "${noteTitle}" with ID: ${noteId}`);

    // 3. CRITICAL: Update task with foreign keys (reminderId and noteId)
    if (reminderId) {
      task.reminderId = reminderId;
    }
    if (noteId) {
      task.noteId = noteId;
    }

    await task.save();
    console.log(
      `  ✅ Task updated with foreign keys - reminderId: ${reminderId}, noteId: ${noteId}`,
    );
    console.log(`✨ Auto-creation completed for task "${task.title}"`);

    return {
      task,
      reminderId,
      noteId,
      reminder: savedReminder,
      note: savedNote,
    };
  } catch (error) {
    console.error(
      `❌ Error auto-creating dependencies for task ${task._id}:`,
      error,
    );
    return { task, reminderId: null, noteId: null, error: error.message };
  }
}

/**
 * Update dependencies when task is updated
 * @param {Object} task - The updated task object
 * @param {Object} updates - What was updated
 */
async function updateDependencies(task, updates, previousValues = {}) {
  try {
    console.log(`🔄 Updating dependencies for task: "${task.title}"`);

    // ================================
    // DUE DATE / TIME UPDATE
    // ================================
    if (updates.dueDate) {
      const oldDate = previousValues.oldDueDate
        ? new Date(previousValues.oldDueDate)
        : null;

      const newDate = new Date(task.dueDate);

      let changeType = "datetime";

      if (oldDate) {
        const oldP = getISTDateParts(oldDate);
        const newP = getISTDateParts(newDate);
        const oldDatePart = `${oldP.year}-${oldP.month}-${oldP.day}`;
        const newDatePart = `${newP.year}-${newP.month}-${newP.day}`;

        const oldTimePart = `${oldP.hour}:${oldP.minute}`;
        const newTimePart = `${newP.hour}:${newP.minute}`;

        const dateChanged = oldDatePart !== newDatePart;
        const timeChanged = oldTimePart !== newTimePart;

        if (dateChanged && !timeChanged) {
          changeType = "date";
        } else if (!dateChanged && timeChanged) {
          changeType = "time";
        } else {
          changeType = "datetime";
        }
      }

      // UPDATE EXISTING REMINDER
      if (task.reminderId) {
        const reminder = await Reminder.findById(task.reminderId);

        if (reminder) {
          reminder.remindAt = task.dueDate;
          reminder.title = task.title;
          await reminder.save();
          console.log(`  ✅ Reminder ${changeType} updated successfully`);
        }
      }
      // CREATE REMINDER IF NOT EXISTS
      else {
        const reminder = new Reminder({
          title: task.title,
          remindAt: task.dueDate,
          taskId: task._id,
          isAutoGenerated: true,
        });

        const savedReminder = await reminder.save();
        task.reminderId = savedReminder._id;
        await task.save();
        console.log(`  ✅ New reminder created`);
      }

      updates.changeType = changeType;
    }

    // ================================
    // TITLE UPDATE
    // ================================
    if (updates.title) {
      if (task.reminderId) {
        const reminder = await Reminder.findById(task.reminderId);
        if (reminder) {
          reminder.title = task.title;
          await reminder.save();
          console.log(`  ✅ Reminder title updated`);
        }
      }

      if (task.noteId) {
        const note = await Note.findById(task.noteId);
        if (note) {
          note.title = task.title;
          await note.save();
          console.log(`  ✅ Note title updated`);
        }
      }
    }

    console.log(`✨ Dependency update completed`);
  } catch (error) {
    console.error(`❌ Error updating dependencies:`, error);
  }
}

/**
 * Delete dependencies when task is deleted
 * @param {string} taskId - Task ID
 */
async function deleteDependencies(taskId) {
  try {
    console.log(`🔄 Deleting dependencies for task ID: ${taskId}`);

    const task = await Task.findById(taskId);

    if (task) {
      if (task.reminderId) {
        await Reminder.findByIdAndDelete(task.reminderId);
        console.log(`  ✅ Deleted reminder: ${task.reminderId}`);
      }
      if (task.noteId) {
        await Note.findByIdAndDelete(task.noteId);
        console.log(`  ✅ Deleted note: ${task.noteId}`);
      }
    }

    const reminderResult = await Reminder.deleteMany({ taskId: taskId });
    const noteResult = await Note.deleteMany({ taskId: taskId });

    if (reminderResult.deletedCount > 0 || noteResult.deletedCount > 0) {
      console.log(
        `  ✅ Cleaned up ${reminderResult.deletedCount} orphaned reminder(s) and ${noteResult.deletedCount} orphaned note(s)`,
      );
    }

    console.log(`✨ Dependency deletion completed`);
    return {
      remindersDeleted:
        reminderResult.deletedCount || (task?.reminderId ? 1 : 0),
      notesDeleted: noteResult.deletedCount || (task?.noteId ? 1 : 0),
    };
  } catch (error) {
    console.error(`❌ Error deleting dependencies:`, error);
    return { remindersDeleted: 0, notesDeleted: 0, error: error.message };
  }
}

/**
 * Get a task with all its dependencies
 * @param {string} taskId - Task ID
 */
async function getTaskWithDependencies(taskId) {
  try {
    const task = await Task.findById(taskId);
    if (!task) return null;

    const reminder = task.reminderId
      ? await Reminder.findById(task.reminderId)
      : null;
    const note = task.noteId ? await Note.findById(task.noteId) : null;

    return { task, reminder, note };
  } catch (error) {
    console.error(`❌ Error fetching task with dependencies:`, error);
    return null;
  }
}

/**
 * Get reminder with its task and note using reminder ID
 * @param {string} reminderId - Reminder ObjectId
 */
async function getReminderWithDependenciesById(reminderId) {
  try {
    const reminder = await Reminder.findById(reminderId);
    if (!reminder) return null;

    const task = reminder.taskId ? await Task.findById(reminder.taskId) : null;
    const note = task?.noteId ? await Note.findById(task.noteId) : null;

    return { reminder, task, note };
  } catch (error) {
    console.error("Error:", error);
    return null;
  }
}

/**
 * Get note with its task and reminder using note ID
 * @param {string} noteId - Note ObjectId
 */
async function getNoteWithDependenciesById(noteId) {
  try {
    const note = await Note.findById(noteId);
    if (!note) return null;

    const task = note.taskId ? await Task.findById(note.taskId) : null;
    const reminder = task?.reminderId
      ? await Reminder.findById(task.reminderId)
      : null;

    return { note, task, reminder };
  } catch (error) {
    console.error("Error:", error);
    return null;
  }
}

/**
 * Get task by note title (find task linked to a note by note title)
 * @param {string} noteTitle - Note title
 * @returns {Promise<Object>} - Task with dependencies
 */
async function getTaskByNoteTitle(noteTitle) {
  try {
    console.log(`🔍 Searching for note with title: "${noteTitle}"`);

    let note = await Note.findOne({
      title: { $regex: new RegExp(`^${noteTitle}$`, "i") },
    });

    if (!note) {
      console.log(`  ⚠️ Exact match not found, trying partial match...`);
      note = await Note.findOne({
        title: { $regex: new RegExp(noteTitle, "i") },
      });
    }

    if (!note && noteTitle.includes("_")) {
      const withoutUnderscore = noteTitle.replace(/_/g, " ");
      console.log(`  🔍 Trying without underscore: "${withoutUnderscore}"`);
      note = await Note.findOne({
        title: { $regex: new RegExp(`^${withoutUnderscore}$`, "i") },
      });
    }

    if (!note && noteTitle.includes(" ")) {
      const withUnderscore = noteTitle.replace(/ /g, "_");
      console.log(`  🔍 Trying with underscore: "${withUnderscore}"`);
      note = await Note.findOne({
        title: { $regex: new RegExp(`^${withUnderscore}$`, "i") },
      });
    }

    if (!note) {
      console.log(`  ❌ No note found matching "${noteTitle}"`);
      return null;
    }

    console.log(`  ✅ Found note: "${note.title}"`);

    if (!note.taskId) {
      console.log(`  ⚠️ Note "${note.title}" has no linked task`);
      return null;
    }

    return await getTaskWithDependencies(note.taskId);
  } catch (error) {
    console.error(`❌ Error fetching task by note title:`, error);
    return null;
  }
}

/**
 * Get task by reminder title (find task linked to a reminder by reminder title)
 * @param {string} reminderTitle - Reminder title
 * @returns {Promise<Object>} - Task with dependencies
 */
async function getTaskByReminderTitle(reminderTitle) {
  try {
    console.log(`🔍 Searching for reminder with title: "${reminderTitle}"`);

    let reminder = await Reminder.findOne({
      title: { $regex: new RegExp(`^${reminderTitle}$`, "i") },
    });

    if (!reminder) {
      console.log(`  ⚠️ Exact match not found, trying partial match...`);
      reminder = await Reminder.findOne({
        title: { $regex: new RegExp(reminderTitle, "i") },
      });
    }

    if (!reminder) {
      console.log(`  ❌ No reminder found matching "${reminderTitle}"`);
      return null;
    }

    console.log(`  ✅ Found reminder: "${reminder.title}"`);

    if (!reminder.taskId) {
      console.log(`  ⚠️ Reminder "${reminder.title}" has no linked task`);
      return null;
    }

    return await getTaskWithDependencies(reminder.taskId);
  } catch (error) {
    console.error(`❌ Error fetching task by reminder title:`, error);
    return null;
  }
}

/**
 * Get task by note ID (find task linked to a note)
 * @param {string} noteId - Note ID
 */
async function getTaskByNoteId(noteId) {
  try {
    const note = await Note.findById(noteId);
    if (!note || !note.taskId) return null;
    return await getTaskWithDependencies(note.taskId);
  } catch (error) {
    console.error(`❌ Error fetching task by note ID:`, error);
    return null;
  }
}

/**
 * Get task by reminder ID (find task linked to a reminder)
 * @param {string} reminderId - Reminder ID
 */
async function getTaskByReminderId(reminderId) {
  try {
    const reminder = await Reminder.findById(reminderId);
    if (!reminder || !reminder.taskId) return null;
    return await getTaskWithDependencies(reminder.taskId);
  } catch (error) {
    console.error(`❌ Error fetching task by reminder ID:`, error);
    return null;
  }
}

/**
 * Search all by keyword - returns task, its reminder, and note together
 */
async function searchAllByKeyword(keyword) {
  try {
    let task = await Task.findOne({
      title: { $regex: new RegExp(keyword, "i") },
    });

    if (task) {
      const reminder = task.reminderId
        ? await Reminder.findById(task.reminderId)
        : null;
      const note = task.noteId ? await Note.findById(task.noteId) : null;
      return { type: "task", data: { task, reminder, note } };
    }

    let reminder = await Reminder.findOne({
      title: { $regex: new RegExp(keyword, "i") },
    });

    if (reminder) {
      const task = reminder.taskId
        ? await Task.findById(reminder.taskId)
        : null;
      const note = task?.noteId ? await Note.findById(task.noteId) : null;
      return { type: "reminder", data: { reminder, task, note } };
    }

    let note = await Note.findOne({
      title: { $regex: new RegExp(keyword, "i") },
    });

    if (note) {
      const task = note.taskId ? await Task.findById(note.taskId) : null;
      const reminder = task?.reminderId
        ? await Reminder.findById(task.reminderId)
        : null;
      return { type: "note", data: { note, task, reminder } };
    }

    return null;
  } catch (error) {
    console.error("Search error:", error);
    return null;
  }
}

module.exports = {
  autoCreateDependencies,
  updateDependencies,
  deleteDependencies,
  getTaskWithDependencies,
  getReminderWithDependenciesById,
  getNoteWithDependenciesById,
  searchAllByKeyword,
  getTaskByNoteId,
  getTaskByReminderId,
  getTaskByNoteTitle,
  getTaskByReminderTitle,
};
