const Task = require("../models/Task");
const Reminder = require("../models/Reminder");
const Note = require("../models/Note");

/**
 * Auto-create reminder and note for a task
 * @param {Object} task - The created task object
 * @returns {Promise<Object>} - Returns the task with reminderId and noteId
 */
async function autoCreateDependencies(task) {
  try {
    console.log(`🔄 Auto-creating dependencies for task: "${task.title}"`);

    let reminderId = null;
    let noteId = null;

    // 1. Auto-create reminder (if task has due date)
    if (task.dueDate) {
      const reminderDate = new Date(task.dueDate);
      reminderDate.setHours(9, 0, 0, 0);
      const reminderTitle = `Reminder: ${task.title}`;
      const reminder = new Reminder({
        title: reminderTitle,
        remindAt: reminderDate,
        taskId: task._id,
        isAutoGenerated: true,
      });

      const savedReminder = await reminder.save();
      console.log(savedReminder);
      reminderId = savedReminder._id;
      console.log(
        `  ✅ Reminder created: "${reminderTitle}" for ${reminderDate}`,
      );
    } else {
      console.log(`  ⚠️ No due date, skipping reminder creation`);
    }

    // 2. Auto-create note
    const noteTitle = `Notes: ${task.title}`;
    const noteContent = `Task: ${task.title}\nPriority: ${task.priority}\nCreated: ${new Date().toLocaleString()}\n\n---\nAdd your notes here...`;

    const note = new Note({
      title: noteTitle,
      content: noteContent,
      taskId: task._id,
      isAutoGenerated: true,
    });

    const savedNote = await note.save();
    noteId = savedNote._id;
    console.log(`  ✅ Note created: "${noteTitle}"`);

    // 3. Update task with references
    if (reminderId) {
      task.reminderId = reminderId;
    }
    if (noteId) {
      task.noteId = noteId;
    }

    await task.save();
    console.log(`  ✅ Task updated with dependency references`);
    console.log(`✨ Auto-creation completed for task "${task.title}"`);

    return {
      task,
      reminderId,
      noteId,
      reminder: reminderId ? await Reminder.findById(reminderId) : null,
      note: noteId ? await Note.findById(noteId) : null,
    };
  } catch (error) {
    console.error(
      `❌ Error auto-creating dependencies for task ${task._id}:`,
      error,
    );
    // Don't throw - we want the task to exist even if dependencies fail
    return { task, reminderId: null, noteId: null, error: error.message };
  }
}

/**
 * Update dependencies when task is updated
 * @param {Object} task - The updated task object
 * @param {Object} updates - What was updated
 */
async function updateDependencies(task, updates) {
  try {
    console.log(`🔄 Updating dependencies for task: "${task.title}"`);

    // Update reminder if it exists and due date changed
    if (task.reminderId && updates.dueDate) {
      const reminder = await Reminder.findById(task.reminderId);
      if (reminder) {
        reminder.remindAt = task.dueDate;
        reminder.title = `Reminder: ${task.title}`;
        await reminder.save();
        console.log(`  ✅ Reminder updated`);
      }
    }

    // Update note title if task title changed
    if (task.noteId && updates.title) {
      const note = await Note.findById(task.noteId);
      if (note) {
        note.title = `Notes: ${task.title}`;
        await note.save();
        console.log(`  ✅ Note title updated`);
      }
    }

    console.log(`✨ Dependency update completed`);
  } catch (error) {
    console.error(`❌ Error updating dependencies:`, error);
  }
}

/**
 * Delete dependencies when task is deleted
 * @param {string} taskId - Task ID
 */
async function deleteDependencies(taskId) {
  try {
    console.log(`🔄 Deleting dependencies for task ID: ${taskId}`);

    const result = await Promise.all([
      Reminder.deleteMany({ taskId: taskId }),
      Note.deleteMany({ taskId: taskId }),
    ]);

    console.log(`  ✅ Deleted ${result[0].deletedCount} reminder(s)`);
    console.log(`  ✅ Deleted ${result[1].deletedCount} note(s)`);
    console.log(`✨ Dependency deletion completed`);

    return {
      remindersDeleted: result[0].deletedCount,
      notesDeleted: result[1].deletedCount,
    };
  } catch (error) {
    console.error(`❌ Error deleting dependencies:`, error);
    return { remindersDeleted: 0, notesDeleted: 0, error: error.message };
  }
}

/**
 * Get a task with all its dependencies
 * @param {string} taskId - Task ID
 */
async function getTaskWithDependencies(taskId) {
  try {
    const task = await Task.findById(taskId);
    if (!task) return null;

    const reminder = task.reminderId
      ? await Reminder.findById(task.reminderId)
      : null;
    const note = task.noteId ? await Note.findById(task.noteId) : null;

    return {
      task,
      reminder,
      note,
    };
  } catch (error) {
    console.error(`❌ Error fetching task with dependencies:`, error);
    return null;
  }
}

module.exports = {
  autoCreateDependencies,
  updateDependencies,
  deleteDependencies,
  getTaskWithDependencies,
};
