const Task = require("../models/Task");
const Reminder = require("../models/Reminder");
const Note = require("../models/Note");

/**
 * Auto-create reminder and note for a task
 * @param {Object} task - The created task object
 * @returns {Promise<Object>} - Returns the task with reminderId and noteId
 */
async function autoCreateDependencies(task) {
  try {
    console.log(`🔄 Auto-creating dependencies for task: "${task.title}"`);

    let reminderId = null;
    let noteId = null;
    let savedReminder = null;
    let savedNote = null;

    // 1. Auto-create reminder (if task has due date)
    if (task.dueDate) {
      const reminderDate = new Date(task.dueDate);
      reminderDate.setHours(9, 0, 0, 0);
      const reminderTitle = `${task.title}`;
      const reminder = new Reminder({
        title: reminderTitle,
        remindAt: reminderDate,
        taskId: task._id,
        isAutoGenerated: true,
      });

      savedReminder = await reminder.save();
      reminderId = savedReminder._id;
      console.log(
        `  ✅ Reminder created: "${reminderTitle}" with ID: ${reminderId}`,
      );
    } else {
      console.log(`  ⚠️ No due date, skipping reminder creation`);
    }

    // 2. Auto-create note
    const noteTitle = `${task.title}`;
    const noteContent = `Task: ${task.title}\nPriority: ${task.priority}\nCreated: ${new Date().toLocaleString()}\n\n---\nAdd your notes here...`;

    const note = new Note({
      title: noteTitle,
      content: noteContent,
      taskId: task._id,
      isAutoGenerated: true,
    });

    savedNote = await note.save();
    noteId = savedNote._id;
    console.log(`  ✅ Note created: "${noteTitle}" with ID: ${noteId}`);

    // 3. CRITICAL: Update task with foreign keys (reminderId and noteId)
    if (reminderId) {
      task.reminderId = reminderId;
    }
    if (noteId) {
      task.noteId = noteId;
    }

    // THIS IS THE KEY LINE - MUST BE HERE
    await task.save();
    console.log(
      `  ✅ Task updated with foreign keys - reminderId: ${reminderId}, noteId: ${noteId}`,
    );
    console.log(`✨ Auto-creation completed for task "${task.title}"`);

    return {
      task,
      reminderId,
      noteId,
      reminder: savedReminder,
      note: savedNote,
    };
  } catch (error) {
    console.error(
      `❌ Error auto-creating dependencies for task ${task._id}:`,
      error,
    );
    return { task, reminderId: null, noteId: null, error: error.message };
  }
}

/**
 * Update dependencies when task is updated
 * @param {Object} task - The updated task object
 * @param {Object} updates - What was updated
 */
async function updateDependencies(task, updates) {
  try {
    console.log(`🔄 Updating dependencies for task: "${task.title}"`);

    // Update reminder if it exists and due date changed
    if (task.reminderId && updates.dueDate) {
      const reminder = await Reminder.findById(task.reminderId);
      if (reminder) {
        reminder.remindAt = task.dueDate;
        reminder.title = `${task.title}`;
        await reminder.save();
        console.log(`  ✅ Reminder updated`);
      }
    } else if (updates.dueDate && !task.reminderId) {
      // If due date added but no reminder exists, create one
      const reminderDate = new Date(task.dueDate);
      reminderDate.setHours(9, 0, 0, 0);
      const reminder = new Reminder({
        title: `${task.title}`,
        remindAt: reminderDate,
        taskId: task._id,
        isAutoGenerated: true,
      });
      const savedReminder = await reminder.save();
      task.reminderId = savedReminder._id;
      await task.save();
      console.log(`  ✅ New reminder created for updated due date`);
    }

    // Update note title if task title changed
    if (task.noteId && updates.title) {
      const note = await Note.findById(task.noteId);
      if (note) {
        note.title = `${task.title}`;
        await note.save();
        console.log(`  ✅ Note title updated`);
      }
    }

    console.log(`✨ Dependency update completed`);
  } catch (error) {
    console.error(`❌ Error updating dependencies:`, error);
  }
}

/**
 * Delete dependencies when task is deleted
 * @param {string} taskId - Task ID
 */
async function deleteDependencies(taskId) {
  try {
    console.log(`🔄 Deleting dependencies for task ID: ${taskId}`);

    const result = await Promise.all([
      Reminder.deleteMany({ taskId: taskId }),
      Note.deleteMany({ taskId: taskId }),
    ]);

    console.log(`  ✅ Deleted ${result[0].deletedCount} reminder(s)`);
    console.log(`  ✅ Deleted ${result[1].deletedCount} note(s)`);
    console.log(`✨ Dependency deletion completed`);

    return {
      remindersDeleted: result[0].deletedCount,
      notesDeleted: result[1].deletedCount,
    };
  } catch (error) {
    console.error(`❌ Error deleting dependencies:`, error);
    return { remindersDeleted: 0, notesDeleted: 0, error: error.message };
  }
}

/**
 * Get a task with all its dependencies
 * @param {string} taskId - Task ID
 */
async function getTaskWithDependencies(taskId) {
  try {
    const task = await Task.findById(taskId);
    if (!task) return null;

    const reminder = task.reminderId
      ? await Reminder.findById(task.reminderId)
      : null;
    const note = task.noteId ? await Note.findById(task.noteId) : null;

    return {
      task,
      reminder,
      note,
    };
  } catch (error) {
    console.error(`❌ Error fetching task with dependencies:`, error);
    return null;
  }
}
/**
 * Get reminder with its task and note using reminder ID (not title)
 * @param {string} reminderId - Reminder ObjectId
 */
async function getReminderWithDependenciesById(reminderId) {
  try {
    const reminder = await Reminder.findById(reminderId);
    if (!reminder) return null;

    const task = reminder.taskId ? await Task.findById(reminder.taskId) : null;
    const note = task?.noteId ? await Note.findById(task.noteId) : null;

    return { reminder, task, note };
  } catch (error) {
    console.error("Error:", error);
    return null;
  }
}

/**
 * Get note with its task and reminder using note ID (not title)
 * @param {string} noteId - Note ObjectId
 */
async function getNoteWithDependenciesById(noteId) {
  try {
    const note = await Note.findById(noteId);
    if (!note) return null;

    const task = note.taskId ? await Task.findById(note.taskId) : null;
    const reminder = task?.reminderId
      ? await Reminder.findById(task.reminderId)
      : null;

    return { note, task, reminder };
  } catch (error) {
    console.error("Error:", error);
    return null;
  }
}

/**
 * Search all by keyword - returns task, its reminder, and note together
 */
/**
 * Search by keyword - returns task with its reminder and note using IDs
 */
async function searchAllByKeyword(keyword) {
  try {
    // First find task by title
    let task = await Task.findOne({
      title: { $regex: new RegExp(keyword, "i") },
    });

    if (task) {
      // Use ID-based lookup (not title-based)
      const reminder = task.reminderId
        ? await Reminder.findById(task.reminderId)
        : null;
      const note = task.noteId ? await Note.findById(task.noteId) : null;
      return { type: "task", data: { task, reminder, note } };
    }

    // Then find reminder by title
    let reminder = await Reminder.findOne({
      title: { $regex: new RegExp(keyword, "i") },
    });

    if (reminder) {
      // Use ID-based lookup
      const task = reminder.taskId
        ? await Task.findById(reminder.taskId)
        : null;
      const note = task?.noteId ? await Note.findById(task.noteId) : null;
      return { type: "reminder", data: { reminder, task, note } };
    }

    // Then find note by title
    let note = await Note.findOne({
      title: { $regex: new RegExp(keyword, "i") },
    });

    if (note) {
      // Use ID-based lookup
      const task = note.taskId ? await Task.findById(note.taskId) : null;
      const reminder = task?.reminderId
        ? await Reminder.findById(task.reminderId)
        : null;
      return { type: "note", data: { note, task, reminder } };
    }

    return null;
  } catch (error) {
    console.error("Search error:", error);
    return null;
  }
}
module.exports = {
  autoCreateDependencies,
  updateDependencies,
  deleteDependencies,
  getTaskWithDependencies,
  getReminderWithDependenciesById, // ← Not exported
  getNoteWithDependenciesById, // ← Not exported
  searchAllByKeyword,
};
