const mongoose = require("mongoose");
const Task = require("./Task");
const { isAbsolute } = require("path");
const NoteSchema = new mongoose.Schema({
  title: String,
  content: { type: String, required: true },

  createdAt: { type: Date, default: Date.now },
  taskId: { type: mongoose.Schema.Types.ObjectId, ref: "Task", default: null },
  isAutoGenerated: { type: Boolean, default: false },
});
module.exports = mongoose.model("Note", NoteSchema);
