const mongoose = require("mongoose");
const ReminderSchema = new mongoose.Schema(
  {
    title: String,
    remindAt: { type: Date, required: true },
    taskId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Task",
      default: null,
    },
    isAutoGenerated: { type: Boolean, default: false },
    completed: { type: Boolean, default: false },
  },
  {
    timestamps: true, // ✅ This adds createdAt and updatedAt automatically
  },
);
module.exports = mongoose.model("Reminder", ReminderSchema);
